### ISSUE TITLE
Fix TLS for diecutfacemasks.org

### ISSUE THREAD

**Issue by DMaendlen** [diecutfacemasks/diecutfacemasks.github.io#6]
https://diecutfacemasks.org creates a certificate warning, this needs to be fixed to ensure user friendly and secure access to the web site.

**Comment by hdznrrd** [comment]
that should be fixed by redirecting the toplevel to www.*.
if i understood the documentation correctly, we cannot add multiple domains to the CNAME file.
the proper way of doing that would likely be a HTTP 301 redirect.
this could be done using a DNS "URL" entry, instead of CNAME/ALIAS

**Comment by dcfmuser** [comment]
done.
